Lots of clean up and some additions: * added expm file creation function * fixed $project references in makefile function * fixed indents

diff --git a/lfe-skel b/lfe-skel
--- a/lfe-skel
+++ b/lfe-skel
@@ -20,7 +20,7 @@ following options:
  -v    display the version number and exit
 ENDUSAGE)
 
-rebarconfig=$( cat <<'ENDCONFIG'
+rebarconfig=$( cat <<ENDCONFIG
 {erl_opts, [debug_info, {src_dirs, ["test"]}]}.
 {lfe_first_files, []}.
 {deps_dir, ["deps"]}.
@@ -37,11 +37,11 @@ rebarconfig=$( cat <<'ENDCONFIG'
    {'lfe-sample-rebar-plugin',
      ".*",
      {git, "git://github.com/oubiwann/lfe-sample-rebar-plugin.git",
-   	"master"}}
+       "master"}}
   ]}.
 ENDCONFIG)
 
-gitignore=$( cat <<'ENDIGNORE'
+gitignore=$( cat <<ENDIGNORE
 deps
 *.sublime-project
 *.sublime-workspace
@@ -52,32 +52,33 @@ ebin/*
 ENDIGNORE)
 
 error () {
-   message=$1
-   echo
-   echo $message
-   echo
-   echo "$usage"
-   exit 1
+    message=$1
+    echo
+    echo $message
+    echo
+    echo "$usage"
+    exit 1
 }
 
-unkonw-command-error () {
-   command=$1
-   error "Unknown command or option: '$command'";
+unknown-command-error () {
+    command=$1
+    error "Unknown command or option: '$command'";
 }
 
 missing-parameter-error () {
-   error "Error: command requires parameter"
+    error "Error: command requires parameter"
 }
 
 not-implemented-error () {
-   error "Error: not yet implemented"
+    error "Error: not yet implemented"
 }
 
 create-makefile () {
-   project=$1
-   makefile=$( cat <<'ENDMAKE'
-PROJECT = $project
-LIB = $project
+    project=$1
+    makefile=$project/Makefile
+    echo "PROJECT = $project" > $makefile
+    echo "LIB = $project" >> $makefile
+    makefiledata=$( cat <<'ENDMAKE'
 DEPS = ./deps
 BIN_DIR = ./bin
 EXPM = $(BIN_DIR)/expm
@@ -98,12 +99,14 @@ FINISH = -run init stop -noshell
 
 get-version:
 	@echo
+	@echo "Getting version info ..."
+	@echo
 	@echo -n app.src: ''
-	@erl -eval 'io:format("~p~n", [ \
-		proplists:get_value(vsn,element(3,element(2,hd(element(3, \
-		erl_eval:exprs(element(2, erl_parse:parse_exprs(element(2, \
-		erl_scan:string("Data = " ++ binary_to_list(element(2, \
-		file:read_file("src/$(LIB).app.src"))))))), []))))))])' \
+	@erl -eval 'io:format("~p~n", [ \\
+		proplists:get_value(vsn,element(3,element(2,hd(element(3, \\
+		erl_eval:exprs(element(2, erl_parse:parse_exprs(element(2, \\
+		erl_scan:string("Data = " ++ binary_to_list(element(2, \\
+		file:read_file("src/$(LIB).app.src"))))))), []))))))])' \\
 		$(FINISH)
 	@echo -n package.exs: ''
 	@grep version package.exs |awk '{print $$2}'|sed -e 's/,//g'
@@ -112,7 +115,12 @@ get-version:
 #>--$ ERL_LIB=some/path make get-install-dir
 #
 # Which would give the following result:
-#>--some/path/$project-1.0.0
+#>--some/path/
+ENDMAKE)
+    echo -en "$makefiledata" >> $makefile
+    echo -en $project >> $makefile
+    makefiledata=$( cat <<'ENDMAKE'
+-1.0.0
 #
 get-install-dir:
 	@echo $(ERL_LIB)/$(PROJECT)-$(shell make get-version)
@@ -126,8 +134,8 @@ $(EXPM): $(BIN_DIR)
 
 get-deps: $(EXPM)
 	rebar get-deps
-	for DIR in $(wildcard $(DEPS)/*); \
-	do cd $$DIR; echo "Updating $$DIR ..."; \
+	for DIR in $(wildcard $(DEPS)/*); \\
+	do cd $$DIR; echo "Updating $$DIR ..."; \\
 	git pull; cd - > /dev/null; done
 
 clean-ebin:
@@ -172,25 +180,31 @@ push-all:
 #
 install: INSTALLDIR=$(shell make get-install-dir)
 install: compile
-	if [ "$$ERL_LIB" != "" ]; \
-	then mkdir -p $(INSTALLDIR)/$(EBIN); \
-		mkdir -p $(INSTALLDIR)/$(SRC); \
-		cp -pPR $(EBIN) $(INSTALLDIR); \
-		cp -pPR $(SRC) $(INSTALLDIR); \
-	else \
-		echo "ERROR: No 'ERL_LIB' value is set in the env." \
-		&& exit 1; \
+	if [ "$$ERL_LIB" != "" ]; \\
+	then mkdir -p $(INSTALLDIR)/$(EBIN); \\
+		mkdir -p $(INSTALLDIR)/$(SRC); \\
+		cp -pPR $(EBIN) $(INSTALLDIR); \\
+		cp -pPR $(SRC) $(INSTALLDIR); \\
+	else \\
+		echo "ERROR: No 'ERL_LIB' value is set in the env." \\
+		&& exit 1; \\
 	fi
 
-upload:
+upload: get-version
+	@echo "Package file:"
+	@echo
+	@cat package.exs
+	@echo
+	@echo "Continue with upload? "
+	@read
 	$(EXPM) publish
 ENDMAKE)
-	echo "$makefile" > $project/Makefile
+    echo -en "$makefiledata" >> $makefile
 }
 
 create-dirs () {
-	project=$1
-	mkdir -p $project/src $project/test
+    project=$1
+    mkdir -p $project/src $project/test
 }
 
 create-library-app-file () {
@@ -237,9 +251,23 @@ ENDAPPFILE)
     echo "$appfile" > $project/src/$project.app.src
 }
 
+create-expmfile () {
+    project=$1
+    expmfile=$( cat <<ENDEXPMFILE
+Expm.Package.new(name: "$project",
+                 description: "PROJECT DESCRIPTION",
+                 version: "0.0.1",
+                 keywords: ["LFE", "Lisp", "Library", "API"],
+                 maintainers: [[name: "YOUR NAME",
+                                email: "YOUR@EMAIL.com"]],
+                 repositories: [[github: "YOUR_GITHUB_NAME/$project"]])
+ENDEXPMFILE)
+    echo "$expmfile" > $project/package.exs
+}
+
 create-test-module () {
     project=$1
-testmodule=$( cat <<ENDAPPFILE
+testmodule=$( cat <<ENDTESTMODULE
 (defmodule ${project}_tests
   (export all)
   (import
@@ -258,19 +286,19 @@ testmodule=$( cat <<ENDAPPFILE
 
 (defun noop_test ()
   (assert-equal 1 2))
-ENDAPPFILE)
+ENDTESTMODULE)
     echo "$testmodule" > $project/test/${project}_tests.lfe
 }
 
 create-module () {
     project=$1
-    module=$( cat <<ENDAPPFILE
+    module=$( cat <<ENDMODULE
 (defmodule $project
   (export all))
 
 (defun run ()
   (quote noop))
-ENDAPPFILE)
+ENDMODULE)
     echo "$module" > $project/src/$project.lfe
 }
 
@@ -317,63 +345,68 @@ ENDREADME)
     echo -e "$readme" > $project/README.rst
 }
 
-create-common-files () {
-   project=$1
-   echo "$rebarconfig" > $project/rebar.config
-   echo "$gitignore" > $project/.gitignore
-   create-makefile $project
-   create-test-module $project
-   create-module $project
-   create-readme $project
+create-project-files () {
+    project=$1
+    echo "$gitignore" > $project/.gitignore
+    echo "$rebarconfig" > $project/rebar.config
+    create-makefile $project
+    create-expmfile $project
+    create-readme $project
 }
 
 create-library-files () {
-   project=$1
-   create-library-app-file $project
-   create-common-files $project
+    project=$1
+    create-library-app-file $project
+    create-module $project
+    create-test-module $project
 }
 
 create-service-files () {
-   project=$1
-   not-implemented-error
+    project=$1
+    not-implemented-error
 }
 
 setup-library-project () {
-   echo "Setting up library project skeleton ..."
-   project=$1
-   create-dirs $project
-   create-library-files $project
-   cd $project && make check
+    echo "Setting up library project skeleton ..."
+    project=$1
+    create-dirs $project
+    create-project-files $project
+    create-library-files $project
+    cd $project && git init && git add * .gitignore && make check
 }
 
 setup-service-project () {
-   #echo "Setting up library project skeleton ..."
-   project=$parameter
-   not-implemented-error
+    #echo "Setting up library project skeleton ..."
+    project=$parameter
+    not-implemented-error
 }
 
 check-parameter () {
-   parameter=$1
-   if [ "$parameter" = "" ]; then
-      missing-parameter-error
-   fi
+    parameter=$1
+    if [ "$parameter" = "" ]; then
+        missing-parameter-error
+    fi
 }
 
 case $command in
-   -h)
-      echo "$usage";
-      exit 0;;
-   -v)
-      echo "$version";
-      exit 0;;
-   library-project)
-      check-parameter $parameter
-      setup-library-project $parameter
-      exit 0;;
-   service-project)
-      check-parameter $parameter
-      setup-service-project $parameter
-      exit 0;;
-   *)
-      unkonw-command-error $command
+    -h)
+        echo "$usage"
+        exit 0
+        ;;
+    -v)
+        echo "$version"
+        exit 0
+        ;;
+    library-project)
+        check-parameter $parameter
+        setup-library-project $parameter
+        exit 0
+        ;;
+    service-project)
+        check-parameter $parameter
+        setup-service-project $parameter
+        exit 0
+        ;;
+    *)
+        unknown-command-error $command
 esac
